import { grepArgs, grepPath } from "./git";

// Bloat questions assume executable logic; data and configuration files need other checks.
const BLOAT_LANGUAGES = new Set([
  "ts",
  "tsx",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "mts",
  "cts",
  "py",
  "go",
  "rs",
  "swift",
  "kt",
  "kts",
  "java",
  "cs",
  "rb",
  "php",
  "dart",
  "scala",
  "groovy",
  "sh",
  "bash",
  "zsh",
  "fish",
  "ps1",
  "lua",
  "ex",
  "exs",
  "c",
  "h",
  "cc",
  "cpp",
  "hpp",
  "zig",
]);

// Skip configuration modules because bloat questions mistake their declarations for unnecessary machinery.
const CONFIG_MODULE = /^[\w-]+\.(config|conf)\.[cm]?[jt]s$|^\.[\w-]+rc\.[cm]?[jt]s$/;

export function isBloatCandidate(path: string, text?: string): boolean {
  const name = path.split("/").pop() ?? path;
  if (CONFIG_MODULE.test(name)) return false;
  const ext = name.includes(".") ? name.split(".").pop()!.toLowerCase() : "";
  // An extensionless script such as ./bootstrap counts when its first line names an interpreter.
  return BLOAT_LANGUAGES.has(ext) || (!ext && !!text?.startsWith("#!"));
}

const GENERATED_NAME = /(\.(generated|g|designer|pb|min)\.\w+$|_pb2(_grpc)?\.py$|_generated\.\w+$)/;

const GENERATED_HEADER =
  /<auto-generated|@generated|Code generated .* DO NOT EDIT|This file (is|was) (automatically )?generated|AUTO-GENERATED/i;

export function isGenerated(path: string, text: string): boolean {
  return GENERATED_NAME.test(path) || GENERATED_HEADER.test(text.slice(0, 1500));
}

/** Count files mentioning each identifier. This is a usage hint, not symbol resolution.
 * Separate listing searches avoid collecting every occurrence of common names. */
export async function countUsage(
  repo: string,
  ref: string,
  path: string,
  names: string[],
): Promise<Map<string, number>> {
  const filesUsing = async (name: string) => {
    const process = Bun.spawn(
      ["git", "-C", repo, "grep", "-l", "-I", "-w", "-F", "-e", name, ...grepArgs(ref), "--", "."],
      { stdout: "pipe", stderr: "ignore" },
    );
    const output = await new Response(process.stdout).text();
    await process.exited;
    const files = output
      .split("\n")
      .filter(Boolean)
      .map((line) => grepPath(line, ref));
    return files.filter((file) => file !== path).length;
  };
  const counts = new Map<string, number>();
  const queue = [...names];
  await Promise.all(
    Array.from({ length: Math.min(8, queue.length) }, async () => {
      for (let name = queue.shift(); name !== undefined; name = queue.shift()) counts.set(name, await filesUsing(name));
    }),
  );
  return counts;
}
